/** @type {import('tailwindcss').Config} */
module.exports = {
  corePlugins: { preflight: false },
  content: [
    "./node_modules/flowbite-react/**/*.js",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./node_modules/tailwind-datepicker-react/dist/**/*.js",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./node_modules/react-tailwindcss-datepicker/dist/index.esm.js",
  ],
  safelist: [
    "xs:col-span-1",
    "xs:col-span-2",
    "xs:col-span-3",
    "xs:col-span-4",
    "xs:col-span-5",
    "xs:col-span-6",
    "xs:col-span-7",
    "xs:col-span-8",
    "xs:col-span-9",
    "xs:col-span-10",
    "xs:col-span-11",
    "xs:col-span-12",
    "sm:col-span-1",
    "sm:col-span-2",
    "sm:col-span-3",
    "sm:col-span-4",
    "sm:col-span-5",
    "sm:col-span-6",
    "sm:col-span-7",
    "sm:col-span-8",
    "sm:col-span-9",
    "sm:col-span-10",
    "sm:col-span-11",
    "sm:col-span-12",
    "col-span-1",
    "col-span-2",
    "col-span-3",
    "col-span-4",
    "col-span-5",
    "col-span-6",
    "col-span-7",
    "col-span-8",
    "col-span-9",
    "col-span-10",
    "col-span-11",
    "col-span-12",
  ],
  theme: {
    container: {
      center: true,
      screens: {
        "2xl": "1280px",
      },
    },
    extend: {
      colors: {
        lula: "rgba(255, 86, 1, 1)",
        lulaNew: "#F07637",
        text_primary: "rgba(51, 51, 85, 1)",
        text_secondary: "rgba(51, 51, 85, 0.5)",
        text_disabled: "rgba(198, 198, 208, 1)",
        button_primary: "rgba(255, 86, 1, 1)",
        button_secondary: "rgba(153, 153, 170, 1)",
        lulaBorder: "#D1D5DB",
        lulaBorder_secondary: "#455773",
        background_secondary: "#E7EAF0",
      },
      screens: {
        "3xl": "1920px",
      },
      fontFamily: {
        abel: ["Abel"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/line-clamp"),
    require("flowbite/plugin"),
  ],
};
